version: '3.8'
services:
  app:
    build: ./app
    container_name: java_app
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana                  # persistent Grafana storage
      - ./grafana/provisioning:/etc/grafana/provisioning  # datasources + dashboard provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards # dashboard JSON files
    depends_on:
      - prometheus

volumes:
  grafana-data:
